
server.port: 8090



spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/planner
    username: postgres
    password: postgres
  liquibase.change-log: classpath:liquibase/changelog.xml


